Add bookings
cuttiecat/java-shareit pull request #5
Opened 2023-09-01 19:51 UTC by cuttiecat

First try add-bookings.

2023-09-02 13:03 UTC, EugeneLenkevich requested changes
Привет, Светлана! Спасибо за PR.

В целом все отлично :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

2023-09-02 13:03 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +            "where booking.booker.id = ?1 and booking.startDate < ?2 and booking.endDate > ?2")
?1

Лучше все же плейсхолдер использовать, так надежней и читается проще :)

where booking.booker.id = :userId

2023-09-02 13:03 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +            "select booking " +
Можно кстати первую строчку опустить, и так работать будет :)
```
            "from Booking booking " +
            "where booking.item in ?1 and booking.startDate < ?2 and booking.status = 'APPROVED'" +
            "order by booking.item.id DESC, booking.startDate DESC"
```

2023-09-02 13:03 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    @Transactional
Они тут работать не будут (вернее только в некоторых случаях ), аннотации надо вешать на реализацию :)

Спринг при старте будет создавать прокси для объекта-реализации, который и будет управлять транзакциями
интерфейс => прокси => реализация

2023-09-02 13:03 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    @Transactional
Вот, а на объекте-реализации аннотации работать будут :)

2023-09-02 13:03 UTC, EugeneLenkevich commented on src/main/resources/schema.sql
> +    description VARCHAR(200),
Кстати, 200 символов для описания точно хватит? :)

2023-09-02 18:44 UTC, cuttiecat commented on src/main/resources/schema.sql
> +    description VARCHAR(200),
Да, вы права. Посмотрела в целом по 2000 символов на товар используется :(

2023-09-02 18:47 UTC, EugeneLenkevich commented on src/main/resources/schema.sql
> +    description VARCHAR(200),
Вроде можно вот так сделать.
description VARCHAR,

2023-09-03 03:11 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-09-05 10:44 UTC, merged