First commit. 15ТЗ
cuttiecat/java-shareit pull request #6
Opened 2023-09-05 11:06 UTC by cuttiecat

Первая попытка.

2023-09-05 18:24 UTC, EugeneLenkevich requested changes
Привет, ! Спасибо за PR.

Отличная работа :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

2023-09-05 18:24 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepositoryImpl.java
> +            "ORDER BY b.start DESC")
"ORDER BY b.start DESC"

В объекте Pageable уже есть возможность задать сортировку, попробуй, может получится указать через него,  т.е. не прибивать ее гвоздями указывая в самом запросе? :)

2023-09-05 18:24 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepositoryImpl.java
> +    @Query("SELECT b " +
```
@Query("FROM Booking AS b " +
            "WHERE b.start .... "
```

Часть  "SELECT b " можно, кстати, опустить, она подставится по умолчанию :)

2023-09-05 18:24 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private static final String SERVICE_LOG = "Сервис бронирования получил запрос на {}{}";
А не кажется что такой лог слегка усложняет чтение отладочной информации, в логе будет куча строк, которые начинаются одинаково, а вся релевантная информация - сильно справа :)

2023-09-05 18:24 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        log.info(CONTROLLER_LOG, "добавление брони: ", bookingDto);
Мне кажется что тут стоит разобраться мы хотим залогировать: если мы хотим залогирновать сами бизнес-операции, то стоит перенести логирование на уровень сервиса, так как это его обязанности (допустим метод сервиса вызвал не контроллер, а задача по расписанию, тогда вызов залогирован тогда не будет), а вот если хотим залогировать http-запросы, то тут есть пара моментов а) эти данные могут сильно забивать логи, потому лучше сделать уровень логированитя - log.debug(...) для них. Далее, если нам надо именно http-запросы, то данных в таком логе недостаточно, в запросе как минимум есть еще заголовки и пр
То есть, надо разобраться что именно мы тут хотим логировать и принять соответствующее решение, иначе просто логи неинформативные будут :)

PS
для логирования http-запросов можешь вот это попробовать, если желание будет
https://github.com/zalando/logbook
как непосредственно прикрутить
https://errorsfixing.com/how-to-instantiate-logbook-in-spring-boot-app/

2023-09-05 18:24 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        Map<Long, List<Comment>> commentMap = commentRepository.findAll().stream()
commentRepository.findAll()

Тут мы вытаскиваем все комментарии из базы. Это опасно, память так быстро закончиться. хочется придумать какое то ограничение чтобы не все из таблицы тянуть, например задать только те ид пользователей, которые попали в диапазон порцию from, size. :)

PS
Вообще, можно руками наверно объекты не раскладывать а написать запрос на JPQL, если получится
И для загрузки ленивых коллекций могут помочь вот такие штуки

 join fetch

![image](https://user-images.githubusercontent.com/94845100/194059305-413c94fd-e9da-40d1-8090-05568e0cc255.png)


https://stackoverflow.com/questions/17431312/what-is-the-difference-between-join-and-join-fetch-when-using-jpa-and-hibernate


Или еще вот, entity graph
https://sysout.ru/entity-graph-v-spring-data-jpa/

2023-09-05 20:50 UTC, cuttiecat commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepositoryImpl.java
> +            "ORDER BY b.start DESC")
Не поняла, как можно сделать ещё проще...

2023-09-06 05:07 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepositoryImpl.java
> +            "ORDER BY b.start DESC")
![image](https://github.com/cuttiecat/java-shareit/assets/109306643/d54cdd5d-f787-43b6-b3c6-22fc19ab1d08)

А сортировку лучше задать через Pageable, в нем есть возможность - вложенный объект Sort

2023-09-06 05:37 UTC, merged

2023-09-06 06:01 UTC, cuttiecat commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepositoryImpl.java
> +            "ORDER BY b.start DESC")
> ![image](https://user-images.githubusercontent.com/109306643/265898178-d54cdd5d-f787-43b6-b3c6-22fc19ab1d08.png)
> 
> А сортировку лучше задать через Pageable, в нем есть возможность - вложенный объект Sort

Случайно мержнула и не знаю как вернуть, точнее не получается переоткрыть пул реквест... Отпрвила на проверку, не смогла разобраться с логированием..

2023-09-06 06:10 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepositoryImpl.java
> +            "ORDER BY b.start DESC")
Закрытый ПР уже не переоткрыть, код то уже смержен. Решить это, конечно, можно, но не будем чтоб репозиторий случайно не поломать (можно откатить комит в мастере или ветку перезаписать, но как показывает практика в этот момент легко ошибиться и не ту кнопку нажать и что то не то потереть)

В общем, из контроллеров лучше логирование бизнес-функциональности убрать, оставить только в сервисах. А то у нас одно и тоже получается что логируется два раза :)