16 ТЗ. Первая попытка.
cuttiecat/java-shareit pull request #8
Opened 2023-09-07 22:55 UTC by cuttiecat

Первая попытка. Аминь.

2023-09-08 05:00 UTC, EugeneLenkevich requested changes
Привет, Светлана! Спасибо за PR.

Какой то странный ПР, только 5 файлов измененных... потому что первый комит, похоже, уже в main смержен. Так лучше не делать, в реfльном проекте могут осерчать :)

А так. В целом все хорошо, докер, модули все на месте. Можно вынести вот эту аннотацию, она там похоже и не нужна

![image](https://github.com/cuttiecat/java-shareit/assets/109306643/56d09f91-5f13-4eb2-b54c-e7395a6009a8)

Далее, предложу следующий рефаторинг

![image](https://github.com/cuttiecat/java-shareit/assets/109306643/8abe6408-9b83-4233-af7d-0b16e417f505)
 
В самом клиенте происходит создание и настройка web-клинента. С архитектурной точки зрения это не очень хорошо, клиент занимается своей настройкой, это не его обязаность. Настройку лучше вынести вовне. Можно сделать конфигурацию для бина web-clients и далее он, настроенный, будет инжектится как и остальные бины.

Единственное, аннотацию @Service надо убрать, вообще, это алтернативный способ объявления бинов: мы можем на класс повесить аннотацию или создать такую вот конфигурацию если требуется провести какую то настройку при создании 

Пример вот, только подправь под свою реализацию

![image](https://user-images.githubusercontent.com/94845100/193436606-1894b4f9-aa6d-4359-adec-0791cef7a4e6.png)


Таким образом мы можем иметь разные настройки клиентов для разных сред: допустим на продакшн-сервере с TLS, сертификатами и пр, на тестововм стенде простое соединение, а для локального запуска мы можем, например, вообще создать заглушку, которая будет возвращать статический текст :)

https://www.baeldung.com/spring-profiles

2023-09-08 10:10 UTC, cuttiecat commented
> Привет, Светлана! Спасибо за PR.
> 
> Какой то странный ПР, только 5 файлов измененных... потому что первый комит, похоже, уже в main смержен. Так лучше не делать, в реfльном проекте могут осерчать :)
> 
> А так. В целом все хорошо, докер, модули все на месте. Можно вынести вот эту аннотацию, она там похоже и не нужна
> 
> ![image](https://user-images.githubusercontent.com/109306643/266506291-56d09f91-5f13-4eb2-b54c-e7395a6009a8.png)
> 
> Далее, предложу следующий рефаторинг
> 
> ![image](https://user-images.githubusercontent.com/109306643/266506465-8abe6408-9b83-4233-af7d-0b16e417f505.png)
> 
> В самом клиенте происходит создание и настройка web-клинента. С архитектурной точки зрения это не очень хорошо, клиент занимается своей настройкой, это не его обязаность. Настройку лучше вынести вовне. Можно сделать конфигурацию для бина web-clients и далее он, настроенный, будет инжектится как и остальные бины.
> 
> Единственное, аннотацию @service надо убрать, вообще, это алтернативный способ объявления бинов: мы можем на класс повесить аннотацию или создать такую вот конфигурацию если требуется провести какую то настройку при создании
> 
> Пример вот, только подправь под свою реализацию
> 
> ![image](https://user-images.githubusercontent.com/94845100/193436606-1894b4f9-aa6d-4359-adec-0791cef7a4e6.png)
> 
> Таким образом мы можем иметь разные настройки клиентов для разных сред: допустим на продакшн-сервере с TLS, сертификатами и пр, на тестововм стенде простое соединение, а для локального запуска мы можем, например, вообще создать заглушку, которая будет возвращать статический текст :)
> 
> https://www.baeldung.com/spring-profiles

Опять смержила с main. Не понимаю почему-то idea стало мержить сразу в main, хотя раньше предлагала выбрать ветку в проекте.

2023-09-08 11:58 UTC, EugeneLenkevich commented
> Опять смержила с main. Не понимаю почему-то idea стало мержить сразу в main, хотя раньше предлагала выбрать ветку в проекте.

Минутку, вообще, мы ничего не мержим сами  в Идее.
Порядок у нас такой
1) создаем ветку от основной
2) комитим в нее наши изменения
3) пушим на гитхаб
4) создаем ПР
5) после аппрува жмем мерж в ПРе, ветка только в этот момент мержится
6) далее в идее переключаемся на основную ветку и жмем пулл чтобы подтянулись все смерженные изменения

2023-09-09 02:04 UTC, cuttiecat commented
Можно попросить вас зачесть этот спринт, а то очень боюсь до дедлайна не успеть отправить. Пыталась сделать рефакторинг, но при коммите почему-то ещё вылезла ошибка codestyle при проверке, про неиспользованный импорт, хотя в приложении он используется.. Не понимаю почему так. И никак не могла исправить это..

2023-09-09 15:39 UTC, EugeneLenkevich commented
> Можно попросить вас зачесть этот спринт, а то очень боюсь до дедлайна не успеть отправить. Пыталась сделать рефакторинг, но при коммите почему-то ещё вылезла ошибка codestyle при проверке, про неиспользованный импорт, хотя в приложении он используется.. Не понимаю почему так. И никак не могла исправить это..

Потри этот комент, на всякий случай :)

2023-09-09 15:40 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-09-09 18:28 UTC, merged